name: Docker Build & Push

on:
  push:
    branches: [main, develop]
    paths:
      - 'api/**'
      - 'web/**'
      - 'docker-compose.yml'
      - 'Dockerfile*'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - service: api
            dockerfile: api/Dockerfile
            context: api
          - service: web
            dockerfile: web/Dockerfile
            context: web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.service }} image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: false
          tags: exitsaas-${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  compose-test:
    name: Test Docker Compose
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Test Docker Compose
        run: |
          docker-compose config > /dev/null
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml config > /dev/null

      - name: Check Dockerfiles
        run: |
          docker run --rm -i hadolint/hadolint < api/Dockerfile
          docker run --rm -i hadolint/hadolint < web/Dockerfile
        continue-on-error: true
